name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: SpaceSniffer.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install .NET 9
    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    # Restore dependencies
    - name: Restore dependencies
      run: dotnet restore $env:Solution_Name

    # Build the solution
    - name: Build
      run: dotnet build $env:Solution_Name --configuration ${{ matrix.configuration }} --no-restore

    # Upload build output as artifact
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: SpaceSniffer-${{ matrix.configuration }}
        path: SpaceSniffer/bin/${{ matrix.configuration }}/
